- README.rst
Did not see a clear example in docs or associated SG work. Save a dev like me a few minutes of google time by adding this prototype to example.
> Addition of template use code snippet

- .travis.yml
- CHANGELOG.md
- sendgrid/version.py
- setup.py
- test/__init__.py
> Updating travis and setup.py for specific python version compatibility

- setup.py
> Tb testing

- sendgrid/message.py
> Upgrade Mail to new-style class, on Python 2.x.

- setup.py
Since they have been added to travis targets already.
> Add Python 3.3, 3.4, 3.5 to setup.py classifiers

- CHANGELOG.md
- README.rst
- example_v2_test.py
- example_v3_test.py
- sendgrid/version.py
- documentation for POST, PATCH, DELETE
- generic emails for sample code
> Added api_keys POST, PATCH, DELETE

- sendgrid/helpers/mail/mail.py
https://github.com/sendgrid/sendgrid-python/issues/189
> Fix for issue 189

- docker/README.md
Add backfilled tag numbers, typo fix
> Update docker readme versions

- setup.py
> #336 ValueError Fix

- .travis.yml
> Install unittest2 explicitely to fix python2.6 builds

- CODE_OF_CONDUCT.md
This pull attempts to resolve the issue #372.
> A new code of conduct file

- examples/contactdb/contactdb.py
- test/test_sendgrid.py
Resolves https://github.com/sendgrid/sendgrid-python/issues/310
> Removed list_id param as it's not required as per the issue #310

- TROUBLESHOOTING.md
Some typos in the troubleshooting documentation
> Fixed some typos

- CONTRIBUTING.md
- README.md
- USAGE.md
- USE_CASES.md
> SEO friendly links for README, CONTRIBUTING, USAGE, and USE_CASES

- README.md
> Moved logo to top and added more badges

- .env_sample
- README.md
#447  
@mbernier edit: closes #447
> Add a .env_sample file and Update README #447

- PULL-REQUEST-TEMPLATE.md
> Added PULL-REQUEST-TEMPLATE

- .github/PULL_REQUEST_TEMPLATE
- PULL_REQUEST_TEMPLATE
#445 
Added a PULL_REQUEST_TEMPLATE.
> Added PULL_REQUEST_TEMPLATE

- test/test_app.py
Added tests for apps.py. Waiting review.
> Add test for apps.py #418

- register.py
- os import is not used
- removes unused import 
> removing unsed import in registry

- USE_CASES.md
Expand on instructions to create API key by linking to SendGrid documentation.
- 
- 
> Add link to additional resource

- examples/helpers/mail/mail_example.py
> Updated def build_personalization

- README.md
> Updated README for more info

- README.md
> readme tag update

- CONTRIBUTING.md
> Minor readability update

- examples/helpers/stats/stats_example.py
- sendgrid/helpers/stats/README.md
- sendgrid/helpers/stats/__init__.py
- sendgrid/helpers/stats/stats.py
- test/test_stats.py
Add helpers to pull stats from user account
Add examples for stats helper
Referencing issue: https://github.com/sendgrid/sendgrid-python/issues/391
> Add stats helper

- CODE_OF_CONDUCT.md
> #671: corrected links in CoC. Hacktoberfest.

- .github/PULL_REQUEST_TEMPLATE
- CONTRIBUTING.md
- Update CONTRIBUTING - contribution guideline to branch off development
> v4 - Update CONTRIBUTING - contribution guideline to branch off development

- USAGE.md
I won't spend much time reading all the guides for this small change, feel free to reject this PR and write it in your own words.
> API key permissions mention in USAGE.md

- LICENSE.txt
- Update the LICENSE.txt file for 2019
- Fixes failing CI tests now that we are in a new year
> Update LICENSE.txt for 2019

- README.md
Fixes lagging version numbers in one version of the README
> docs: Update readme supported versions

- sendgrid/helpers/mail/subject.py
Fixes a typo "Subjuct" -> "Subject"
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
> docs: Fixed Subject typo

- USAGE.md
- examples/senderauthentication/senderauthentication.py
- use_cases/domain_authentication.md
* Whitelabel = Sender Authentication
* Domain Whitelabel = Domain Authentication
* IP Whitelabel = Reverse DNS
* Link Whitelabel = Link branding
Relates to #687 and #734
> docs: remove last references of "whitelabel"

- sendgrid/helpers/mail/file_content.py
typo fix in sendgrid/helpers/mail/file_content.py
> docs: fixed typo in sendgrid/helpers/mail/file_content.py

- test/requirements.txt
https://github.com/pallets/flask/issues/4455
> chore: fix flask dependency test issues

- examples/helpers/mail_example.py
> chore: Update mail_example.py

- README.md
Better Personalization object example link
> docs: Fix link that has drifted

- .github/workflows/pr-lint.yml
> misc: Upgrade GitHub Action pr-lint.yml

- .github/workflows/test-and-deploy.yml
> misc: Upgrade GitHub Action test-and-deploy.yml

- .github/workflows/lint-python.yml
- .github/workflows/test-and-deploy.yml
- LICENSE
Similar to https://github.com/sendgrid/sendgrid-php/pull/1115. Docker-compose v2 is default for github actions now. In order to not break the existing script, we install docker-compose v1.
> chore: install docker-compose
