- setup.py
- test/__init__.py
There's no reason to use unittest2 in Python 2.7:
* Everything that unittest2 adds is already present in Python 2.7.
* Older versions of unittest2 has a nasty bug whereby its base class does not call super(); this
can result in some mix-in class's setUp()s not being called at all.
* It's no longer maintained.
> Remove unittest2 in Python 2.7.

- .travis.yml
- MIT.LICENSE
- README.rst
- test/test_mail_v2.py
- tox.ini
> Test support for Python 3.3, 3.4 and 3.5

- MANIFEST.in
MIT License is template based and should be distributed together within the source tarball.
> Include MIT.LICENSE in release tarball

- sendgrid/sendgrid.py
Instead of having the timeout hardcoded in _make_request I changed it to be part of the opts that can be passed when creating a SendGridClient object. 
For example:
```sg = sendgrid.SendGridClient(MY_SENDGRID_KEY, **{'timeout': 45})```
> change timeout to opts variable

- setup.py
This updates the Python [smtpapi](https://github.com/sendgrid/smtpapi-python) library to 0.3.1, the latest version that has been released.
This closes https://github.com/sendgrid/sendgrid-python/issues/160.
> Update smtpapi to 0.3.1

- sendgrid/helpers/mail/mail.py
- test/test_mail.py
Fix https://github.com/sendgrid/sendgrid-python/issues/232
> Substitutions allow non-strings for values

- sendgrid/helpers/inbound/README.md
Hi @thinkingserious,
While looking into the one-click deployment, I noticed the command `heroku clone` is deprecated. It is now `heroku git:clone`. For this example, it actually won't work. Cloning an application deployed with the platform API (in this case the Heroku Button click) clones an empty repository: https://kb.heroku.com/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository
The best approach is to clone the repo normally and add the remote with `heroku git:remote`
> Update deprecated Heroku command

- .travis.yml
- CONTRIBUTING.md
- README.md
- setup.py
- tox.ini
```
Prism Shut Down
----------------------------------------------------------------------
Ran 238 tests in 31.093s
OK
/Users/andrii/.pyenv/versions/3.6.0/lib/python3.6/subprocess.py:761: ResourceWarning: subprocess 60544 is still running
__________________________________________________________________________ summary __________________________________________________________________________
py36: commands succeeded
congratulations :)
```
> Added python 3.6 to tox file

- USE_CASES.md
Add document for https://github.com/sendgrid/sendgrid-python/issues/270
Need to use `base64.b64encode(data).decode()` because in python3, `b64encode` returns `bytes` instead of `string`
Reference:
https://docs.python.org/2/library/base64.html
https://docs.python.org/3/library/base64.html
> Add 'Sending email with attachment' Use Case

- sendgrid/__init__.py
- sendgrid/helpers/inbound/__init__.py
- sendgrid/helpers/inbound/config.py
- sendgrid/helpers/inbound/parse.py
- sendgrid/helpers/inbound/send.py
- sendgrid/helpers/mail/__init__.py
- sendgrid/helpers/mail/mail.py
- sendgrid/sendgrid.py
- setup.py
- test/prism.sh
- test/test_config.py
- test/test_mail.py
- test/test_parse.py
- test/test_sendgrid.py
According to [CONTRIBUTING](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#style-guidelines--naming-conventions) code should pass all pep8 and flake8 errors
On master branch we can see 
```
(python-sedgrid) ~/sendgrid-python$ flake8 . | wc -l
1201
OR
pep8 . | wc -l
1033
```
The goal of this PR to fix all errors.
```
flake8 test/ | wc -l 
test/test_mail.py:212:80: E501 line too long (3359 > 79 characters)
```
```
flake8 sendgrid/ wc -l
```
```
----------------------------------------------------------------------
Ran 238 tests in 32.903s
OK
```
```
pip install flake8 pep8 isort
```
> Improve code quality

- setup.py
Sendgrid tests are installed into `<python_sitelib>/test` which may cause conflicts with other packages. We have run into this when building a package for Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1309244)
The solution would be to either exclude tests or install them under sendgrid directory (`<python_sitelib>/sendgrid/test`).
> Exclude test package

- sendgrid/helpers/mail/mail.py
- test/test_mail.py
> refactor helpers using property getter/setter

- sendgrid/sendgrid.py
- test/test_sendgrid.py
Sendgrid API has an (as yet) undocumented feature allowing parent accounts to impersonate
subusers by including an HTTP header "On-Behalf-Of" in each API request.
This commit enables setting the value for impersonation when creating the
Sendgrid API Client instance.
> Add ability to impersonate subuser

- sendgrid/sendgrid.py
- test/test_sendgrid.py
Because of the way SendGridAPIClient and python_http_client are implemented, request headers are always cached. This becomes a problem when executing a sequence of API requests that require varying request header values using the same SendGridAPIClient instance.
This method allows the caller to reset the request headers on the client instance to their default.
> Add ability to reset request headers on client attribute

- CONTRIBUTING.md
- README.md
- activate.sh
- docker/Dockerfile
- docker/README.md
- docker/USAGE.md
- docker/entrypoint.sh
- test/test_sendgrid.py
- tox.ini
Add a Docker container to make it easier to try out or contribute to sendgrid-python.
- Add Dockerfile, startup shell script, readme
- Update+improve `tox.ini`
- Prism install bugfix
Note: Don't approve until sendgrid/python Docker Hub has been created + linked.  Also, should probably be squashed based on # of tiny commits.
> Add Docker for easy usage

- USAGE.md
Change example code for "retrieve all campaigns" to use the default parameters of limit 10, no offset instead of getting a single campaign with offset 1.  This threw me for a loop a couple weeks ago when I was getting started.
> Change usage example "retrieve all campaigns"

- sendgrid/helpers/mail/mail.py
- test/test_mail.py
This PR addresses issue #334 
The issue was with using unicode values in substitutions. In this PR, I removed forced casting to ascii for values used with Substitutions. It seems that other helpers don't cast values to ascii.
Example code that would cause an error:
`personalization.add_substitution(Substitution("%city%", u"Αθήνα"))`
I created a simple test to see that the Substitutions helper can now handle a unicode string. All tests pass.
I also tested this in an end-to-end workflow, where we submitted data into our form and received a live email with unicode values where expected.
This is my first public pull request on Github, please let me know if I am missing anything required here.
> Permit unicode string values with Substitution helper

- README.md
The link was broken at the point in the README.md at 
[Sign the CLA to Create a Pull Request](https://github.com/sendgrid/sendgrid-open-source-templates/tree/master/CONTRIBUTING.md#cla)
Fixed it to
[Sign the CLA to Create a Pull Request](https://cla.sendgrid.com/sendgrid/sendgrid-python)
instead.
> Updating README.md to fix a broken link

- USE_CASES.md
Using `asyncio`, demonstrated way to send mail in non-blocking manner.
> Asynchronous Mail Send example added to USE_CASES.md

- .travis.yml
- CONTRIBUTING.md
- test/prism.sh
- test/test_sendgrid.py
This changes the install method used in unittests to test/prism.sh script.
prism.sh downloads latest stable (pre 2.0alpha - currently v0.6) and installs it into ~/bin directory.
Unittests will check for prism command in the PATH and few known locations (among them ~/bin dir) and if prism is not found, it will launch the prism script to install it and use the newly installed binary.
CONTRIBUTING page was updated with new procedure info
Fixes #311
> Install prism with non superuser account 

- .coveragerc
- .gitignore
- .travis.yml
- README.md
- tox.ini
This should close #251 
You might want to create separate codecov.io account for sendgrid-python project.
After this, the badge url should be changed in README.md
> Add code coverage check and codecov.io badge

- test/test_mail.py
Add a simple test to prevent the regression of #308, #287 
@mbernier edit: fix #308
> Add test to prevent a regression when disabling click tracking

- README.md
The current codecov badge is showing the code coverage of a fork of the repo and not the official one. Updated it to show the code coverage for official repo.
> Updated Codecov badge to Official repo link

- sendgrid/helpers/mail/mail.py
- test/test_email.py
> Allows users to submit rfc822 formatted email addresses

- .gitignore
- USE_CASES.md
- sendgrid.env
Adds documentation mentioned in issue #383
> Adds how to set up domain whitelabel and how to view email statistics

- test/test_config.py
> Increase config.py coverage

- register.py
-First File is opened using the with context manager
-Broke two long strings into multiple lines
-Add space between arguments in a method call
> Use with context manager and a few PEP8 changes.

- docker/Dockerfile
Fix #426: Attempt to sync before executing shell command
> Fix #426: Attempt to sync before executing shell command

- examples/helpers/mail/mail_example.py
> modularize lengthy method

- test/test_sendgrid.py
Addresses #419 
I added tests for the two api key setter methods in sendgrid.py (apikey and api_key). 
@mbernier edit: closes #419
> Add tests for sendgrid.py apikey and api_key setters

- USAGE.md
> Find a little bug in case

- LICENSE.txt
This PR fixes #491 
The date-range mentioned in LICENSE file is outdated, this PR updates the date-range of [license](https://github.com/sendgrid/sendgrid-python/blob/master/LICENSE.txt) file.
> Updated date-range in LICENSE file 

- TROUBLESHOOTING.md
- USE_CASES.md
- Documented the new error handling functionality from python-http-client as per #442 
> Documented the new error handling functionality from python-http-client

- test/test_project.py
- Adds project based unit tests to the repo. These check specific files exist.
- There was the following errors:
```
(sendgrid-python) ∅ killa/sendgrid-python ‹pjhampton/add-tests*?› » python test/test_project.py                      146 ↵
....F.F.........
======================================================================
FAIL: test_docker_compose (__main__.ProjectTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test_project.py", line 16, in test_docker_compose
self.assertEqual(True, os.path.isfile('docker-compose.yml'))
AssertionError: True != False
======================================================================
FAIL: test_env (__main__.ProjectTests) …
```
> Add Project tests

- test/test_sendgrid.py
Fixes #474 
- Added a test to ensure license year is current
- Test currently fails because MASTER has 2012-2016, which has been rectified by #477 
> Test to check year in LICENSE.txt

- LICENSE.txt
#473
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] I have added necessary documentation about the functionality in the appropriate .md file
- [N/A] I have added in line documentation to the code I modified
- Updates the license file to the current year
> Updated the license file

- examples/user/user.py
@mbernier edit: Related to #464
> removed the trailing white spaces 

- CONTRIBUTING.md
- README.md
- Updates contributing.md to include a section on code review.
> include code reviews section - Fixes #525

- proposals/mail-helper-refactor.md
I found these typography during study on the proposal spec. 
Changes proposed in this pull request:
- Change variable from `tos` to `to_emails` on Send Multiple Emails to Multiple Recipients example
- Change typo of `to_email` to `to_emails` on Kitchen Sink example
- Change attribute `headers` to be `header` on Kitchen Sink example
- Change attribute `global_headers` to be `global_headers` on Kitchen Sink example
connect to #347
> Fix typography on mail helper refactor proposal

- examples/helpers/mail/mail_example.py
> fix examples to use the correct method

- register.py
- sendgrid/helpers/inbound/send.py
- sendgrid/helpers/mail/asm.py
- setup.py
When opening text files in few places, the code relies on system default encoding being set to UTF-8.
This is safe enough in general, but there are certain corner cases like #379, where default one is e.g. ASCII (for whatever reason).
The pull request changes code to use UTF-8 encoding explicitly, without relying on the system defaults.
EDIT: There is another commit fixing a unit test (`test_asm_display_group_limit`), since that was failing the build, coming from master rebase. 
EDIT2: The "reduced" code coverage is because of added import statements - so this is a false positive in fact.
> Provide utf-8 as encoding explicitly when opening text files

- sendgrid/helpers/mail/ganalytics.py
Fixes #498 
- Reduces the complexity of get and __init__ method
> Fix method_complexity issue in sendgrid/helpers/mail/ganalytics.py Fixes #498

- CONTRIBUTING.md
- USAGE.md
- Fixed typo errors in USAGE.md and CONTRIBUTING.md
> Updated USAGE.md and CONTRIBUTING.md

- CONTRIBUTING.md
> Corrected grammatical error in CONTRIBUTING.md

- README.md
- TROUBLESHOOTING.md
- 
Fixing the link to use cases markdown file in the README and TROUBLESHOOTING guide
-
> fixing link to use cases readme

- sendgrid/helpers/mail/mail.py
- 
Allows for optional params for the Mail object to be applied even if not all of them are supplied.
- 
> Ensure params are applied independently

- sendgrid/helpers/mail/personalization.py
- test/test_mail.py
Trying to set `substitutions` directly rather than with `add_substitution` was causing an infinite regress
- the setter for `Personalization.substitutions` was incorrectly referencing `self.subtitutions` rather than `self._substitutions`
- I added a very simple testcase.
> Fix `Personalization.substitutions` setter

- TROUBLESHOOTING.md
editted "our use cases" link
- updates link in Troubleshooting readme to direct to correct use cases link
> update TROUBLESHOOTING.md to link to correct use cases page

- use_cases/README.md
- use_cases/flask_heroku.md
> Add a tutorial to deploy a simple "Hello Email" app on Heroku

- sendgrid/helpers/mail/mail.py
#587
- Change type of category in Mail.add_category from string to Category to prevent warning from some editors
> Issue #587 Change type of category in Mail.add_category from string to Category

- examples/helpers/mail/mail_example.py
Fixes #547 
Closes #547 
- added comment to specify that attachments need to be base64 encoded
- 
> Issue #547: Added comment for attachments to be base64 encoded #patch

- docker/Dockerfile
#584 
- Since we install python with `--no-install-recommends` flag it will not bundle `pip`. So I add command to install `pip` in `python3.6`
- Fix some `pip` install command
> #Issue584 Fix docker build

- examples/helpers/mail_example.py
- sendgrid/helpers/mail/personalization.py
- test/test_mail.py
- use_cases/transational_templates.md
Adds support for dynamic templates
Fixes #591
> Adds support for dynamic template data in personalizations

- README.md
- Fix broken link in the README
- 
> fixes #610

- requirements.txt
- Fix syntax error in requirments file
> Fix format of dependency `pytest`

- .github/PULL_REQUEST_TEMPLATE
- CONTRIBUTING.md
- README.md
- sendgrid/__init__.py
- sendgrid/helpers/endpoints/ip/unassigned.py
- sendgrid/sendgrid.py
- use_cases/aws.md
- use_cases/slack_event_api_integration.md
- use_cases/transational_templates.md
Make it clear that the link is a redirect to an email and not to any members page or developer team page
- 
- 
> Update README.md by including email

- sendgrid/helpers/mail/email.py
- test/test_email.py
- Escapes common CSV delimiters in Email.name
> Quote names containing comma or semicolon

- sendgrid/helpers/mail/README.md
Fixes #635
- Fixes the broken 'examples' link in the mail helper readme.
> Fix broken link for mail example

- README.md
Fixes #635 
Closes #636 
Redirection link of the helper's mail_example.py file
- Fixes the broken example url path in the mail helper README.
- Closes PR #636 which does not redirect the changed url path to the helper's example file.
> Fix helper mail_example redirection link

- .travis.yml
- setup.py
- tox.ini
Like #615 but for the v4 branch.
- Add support for Python 3.7
- A small workaround is needed for Travis CI, see https://github.com/travis-ci/travis-ci/issues/9815
> v4: Add support for Python 3.7

- test/test_spam_check.py
- This adds simple tests for the spam check class.
- I'm simply getting my feet wet in this repo and think that writing tests is a good and productive start. Happy to hear feedback!
> Add unit tests for spam check

- sendgrid/helpers/mail/mail.py
- test/test_mail.py
- Allow direct creation of Mail object from an instance of EmailMessage
> Allow creation of Mail from EmailMessage

- CODE_OF_CONDUCT.md
- Change attribution links into bullet points to match CoC in other Sendgrid repos.
> Correct attribution links formating

- sendgrid/helpers/mail/validators.py
Same as https://github.com/sendgrid/sendgrid-python/pull/698 but for the v4 branch. 
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added necessary documentation about the functionality in the appropriate .md file
- [n/a] I have added in line documentation to the code I modified
- Use raw-string notation for regex to avoid invalid escape sequence
From the [`re` docs](https://docs.python.org/2/library/re.html#module-re):
> Regular expressions use the backslash character (`'\'`) to indicate special forms or to allow special characters to be used without invoking their special meaning. This collides with Python’s usage of the same character for the same purpose in string literals; for example, to match a literal backslash, one might have to …
> v4: Use raw-string notation for regex to avoid invalid escape sequence

- .gitignore
- CONTRIBUTING.md
- docker/USAGE.md
- sendgrid.env
- use_cases/aws.md
Duplicate of #668 against v4
There were some conflicting configuration details, namely .env_sample,
and sendgrid.env. I've opted for .env_sample, as sendgrid.env
actually seemed to be incorrect.
> Cleanup Env Documentation

- README.md
#717 
On the website its mentioned that Send up to 40,000 emails for 30 days, then send 100 emails/day free forever but it has not been mentioned in the README.
> Updation in prerequisites

- use_cases/README.md
- use_cases/sending_html_content.md
- Resolves #354 by adding a use case for generating plain text when only HTML content is available.
> Add use case for generation of Plain Text Content from HTML

- FIRST_TIMERS.md
- Created Documentation for the First-time Contributors to ease their collaborations in a profound manner
> Created First-timers.md File

- use_cases/aws.md
- use_cases/error_handling.md
> API Key typo

- sendgrid/helpers/mail/footer_settings.py
- sendgrid/helpers/mail/open_tracking.py
- sendgrid/helpers/mail/subscription_tracking.py
- [x ] I acknowledge that all my contributions will be made under the project's license
- [x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them
- [ x] I updated my branch with the master branch
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation about the functionality in the appropriate .md file
- [ x] I have added in line documentation to the code I modified
- This PR changes the in-line documentation of the objects in each commit. The types sepcifed for items in MailSettings and tracking Settings specify type string when it really should be a type object
If you have questions, please send an email to [Twilio …
> Update type requirements used for multiple objects. 

- examples/mail/mail.py
Attachment example doesn't have the valid MIME type for PDF. The repo says PDF but should be application/pdf. Our helpers have the correct MIME type in their Type param, https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail_example.py#L88 .
- Updates JSON example to have matching example with Helper library and add valid MIME type for attachments. 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.
> Update mail.py for attachment example.

- examples/helpers/README.md
- examples/helpers/mail_example.py
Fixes #817
- This updates the Helper example to follow the v6 API
> Handle new API in the helper example

- use_cases/attachment.md
- removes duplicated imports and non used imports
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.
> chore: clean up imports

- sendgrid/sendgrid.py
Minor Change
- 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.
> chore: Clean up sendgrid.py

- MANIFEST.in
> fix: add config.yml file to pypi distribution files

- README.md
@misterdorm The link to /mail/send Helper looked fine. Please provide details as to where it should direct to.
- Made changes to #633 
> Updated link to direct to #L9

- USAGE.md
- Replaces "visible by recipient" by "visible to recipient"
> docs: Give preference to 'to' after visible

- README.md
Code snipped provided is throwing error  "TypeError: Object of type Email is not JSON serializable"
Fixes.:
1) Changed "to_email = To("test@example.com") " to to_email = To("test@example.com")
2) mail = Mail(from_email, subject, to_email, , content) to mail = Mail(from_email, to_email, subject, , content)
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
> docs: fix code snippet in README

- Makefile
- examples/helpers/eventwebhook/eventwebhook_example.py
- requirements.txt
- sendgrid/__init__.py
- sendgrid/helpers/eventwebhook/__init__.py
- sendgrid/helpers/eventwebhook/eventwebhook_header.py
- sendgrid/helpers/inbound/config.py
- test/test_eventwebhook.py
When enabling the "Signed Event Webhook Requests" feature in Mail Settings, Twilio SendGrid will generate a private and public key pair using the Elliptic Curve Digital Signature Algorithm (ECDSA). Once that is successfully enabled, all new event posts will have two new headers: X-Twilio-Email-Event-Webhook-Signature and X-Twilio-Email-Event-Webhook-Timestamp, which can be used to validate your events.
This SDK update will make it easier to verify signatures from signed event webhook requests by using the VerifySignature method. Pass in the public key, event payload, signature, and timestamp to validate. Note: You will need to convert your public key string to an elliptic public key object in order to use the VerifySignature method.
> feat: verify signature from event webhook

- sendgrid/helpers/mail/dynamic_template_data.py
- sendgrid/helpers/mail/email.py
- sendgrid/helpers/mail/mail.py
- sendgrid/helpers/mail/personalization.py
- test/test_mail_helpers.py
- use_cases/send_multiple_emails_to_multiple_recipients.md
Fixes https://github.com/sendgrid/sendgrid-python/issues/899
This is helpful when sending multiple emails to multiple recipients. You can now include the dynamic template data with the recipient which will then be included in the personalization.
> feat: add support for dynamic template data to Email class

- sendgrid/helpers/stats/stats.py
This adds docstrings to all the classes in the [stats.py](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/stats/stats.py) file.
> docs: added docstrings to Stats classes

- setup.py
Fixes #913
Adds starkbank-ecdsa dependency to list of package dependencies.
> fix: add dependency to install requires

- sendgrid/helpers/mail/mail.py
- test/test_mail_helpers.py
Fixes https://github.com/sendgrid/sendgrid-python/issues/778
Validated values at runtime for a clearer error message for when someone sets `to_emails` to a list of lists
> fix: type validation on to_emails parameter on mail object

- sendgrid/helpers/mail/mail.py
- test/test_mail_helpers.py
Fixes issue raised in comments of #920
> fix: allow general email type for to_emails

- examples/helpers/mail_example.py
> docs: correct attachment example

- use_cases/sending_html_content.md
The code sample in `sendgrid-python/blob/main/use_cases/sending_html_content.md` were broken. There were two problems. One undefined variable(`mail`) and one runtime error (`ValueError: Please use a To, Cc or Bcc object.`).
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x ] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [x ] I have titled the PR appropriately
- [x ] I have updated my branch with the main branch
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added the necessary documentation about the functionality in the appropriate .md file
- [x ] I have added inline documentation to the code I …
> docs: Sending HTML email example is broken

- sendgrid/helpers/mail/batch_id.py
Fixes names in docstrings referring to SendAt object methods. As is, the docstrings are confusing and/or distracting.
> fix: replace names in BatchId docstrings

- sendgrid/helpers/mail/__init__.py
- sendgrid/helpers/mail/bypass_bounce_management.py
- sendgrid/helpers/mail/bypass_spam_management.py
- sendgrid/helpers/mail/bypass_unsubscribe_management.py
- sendgrid/helpers/mail/mail_settings.py
- test/test_mail_helpers.py
- use_cases/kitchen_sink.md
- Resolves https://github.com/sendgrid/sendgrid-python/issues/981
Adds support for the following v3 suppression bypass filters, detailed [here](https://sendgrid.com/docs/ui/sending-email/index-suppressions/) 
- `bypass_spam_management`
- `bypass_bounce_management`
- `bypass_unsubscribe_management`
> feat: add v3 bypass filters

- sendgrid/helpers/mail/mail.py
Update the type of Mail.to()'s parameter to_emails to match how this method accepts list of str and list of tuple for to_emails as well.
> docs: Update to_emails type

- sendgrid/helpers/mail/email.py
- test/test_email.py
Jira ticket: https://issues.corp.twilio.com/browse/DI-1463
> chore: remove logic adding quotes to names containing , and ;

- sendgrid/helpers/mail/mail.py
- test/test_mail_helpers.py
- use_cases/send_a_single_email_to_a_single_recipient.md
Add the `reply_to` keyword argument to `helpers.mail.Mail`.
Otherwise, we must create the Mail and then set the reply_to with
its setter (and we have to dig the repository to find out).
I didn't run the tests locally.
> feat: add reply_to to helpers.Mail

- sendgrid/helpers/mail/mail.py
- test/test_mail_helpers.py
- use_cases/send_a_single_email_to_a_single_recipient.md
Remove duplicated `reply_to` in the `mail` helper
Fixes #1001 
Revert #999
> chore: get rid of reply_to in mail helper

- .travis.yml
- README.md
> chore: test against v3.9

- requirements.txt
- setup.py
Security vulnerability in starbank-ecdsa <=2.0.0
see https://github.com/advisories/GHSA-9wx7-jrvc-28mm for details
Fixes #1023
> chore: fix vulnerability in starbank-ecdsa dependency

- use_cases/error_handling.md
> docs: remove leading spaces on error handling example

- setup.py
The import is unused and distutils is scheduled for removal in Python 3.12. So this can be safely removed.
```
python3.10             
Python 3.10.0b1 (default, May  6 2021, 02:44:57) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.file_util import copy_file
<stdin>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
> chore: Remove unused import from distutils

- use_cases/transactional_templates.md
In the transaction email template example the `json` import is unused.
> docs: Removing unused json import

- .github/workflows/test-and-deploy.yml
- setup.py
> feat: Add Python 3.11 to the testing

- sendgrid/helpers/mail/mail.py
- test/unit/test_mail_helpers.py
- use_cases/send_a_single_email_with_multiple_reply_to_addresses.md
`reply_to_list` exists in the sendgrid API v3, but it has never been implemented for the python api.
I added tests and a use case, but I didn't see any other docs. But this property already exists in the [official docs](https://docs.sendgrid.com/api-reference/mail-send/mail-send#multiple-reply-to-emails).
Also, I never code in python, so I may have made some mistakes here. Just kind of based this off of the existing code and some googling.
- [-] I have added inline documentation to the code I modified
> feat: Add reply_to_list functionality

- README.rst
- test/requirements.txt
Fix build by removing dead dependency.
Per the announcment:
https://about.codecov.io/blog/message-regarding-the-pypi-package/ coddev deprecated their pypi package on april 12, 2023 causing the build to break
We no longer are registered at codedev:
https://app.codecov.io/gh/sendgrid/sendgrid-python "This repo has been deactivated"
> test: removing codedev test dependency

- .github/workflows/test-and-deploy.yml
- .gitignore
- LICENSE
- requirements.txt
- sendgrid/__init__.py
- sendgrid/base/__init__.py
- sendgrid/base/auth_strategy.py
- sendgrid/base/client_base.py
- sendgrid/base/url_builder.py
- sendgrid/base/values.py
- sendgrid/client.py
- sendgrid/converters/serialize.py
- sendgrid/exceptions/__init__.py
- sendgrid/http/__init__.py
- sendgrid/http/http_client.py
- sendgrid/http/request.py
- sendgrid/http/response.py
- sendgrid/utility/__init__.py
- setup.py
As a part of autogeneration of code. http client, client exception has been created
> chore: created http client, serialiser

- .github/workflows/test-and-deploy.yml
- Makefile
- setup.py
- test/requirements.txt
- tox.ini
> feat: add support for python3.12 and 3.13

- .github/workflows/test-and-deploy.yml
- setup.py
werkzeug package is using https://github.com/sendgrid/sendgrid-python/blob/main/sendgrid/helpers/inbound/parse.py#L6. I think its mandatory package here.
In recently at airflow our CI is failing due to werkzeug package missing.
https://github.com/apache/airflow/actions/runs/14342959080/job/40206921048?pr=48819#step:6:2431 
> chore: Add werkzeug package to setup file

- setup.py
Following up on #1085, adding ecdsa in setup.py as well
> chore: update ecdsa in setup.py

- setup.py
From werkzeug changelog:
version 2.3.5 added support for Python 3.12 https://github.com/pallets/werkzeug/blob/main/CHANGES.rst#version-235
version 2.2.0 added/fixed support for Python 3.11 https://github.com/pallets/werkzeug/blob/main/CHANGES.rst#version-220
version 2.3.0 dropped support for Python 3.7 https://github.com/pallets/werkzeug/blob/main/CHANGES.rst#version-230
I couldn't find entries for all versions in the changelog but this should better reflect the lower and upper binds
> chore: Relax werkzeug version
